spring:
  # 개발 환경 기본 값 설정
  profiles:
    default: local

  # 요청 URI로 리소스를 찾을 수 없는 경우 NoHandlerFoundException 예외 발생 시키기
  mvc:
    throw-exception-if-no-handler-found: true

  # ResourceHttpRequestHandler에 대한 매핑 끄기
  web:
    resources:
      add-mappings: false

# MyBatis 설정
mybatis:
  # 마이바티스에서 타입 정보를 사용할 때 패키지 이름을 적어줘야하는데, 여기에 명시하면 패키지 이름 생략 가능
  type-aliases-package: com.programmers.ticketparis.domain
  # underscore를 camel-case 자동 변환
  configuration:
    map-underscore-to-camel-case: true
  # mapper관련 xml파일이 존재하는 디렉터리의 위치
  mapper-locations: classpath:mapper/**/*.xml
  type-handlers-package: com.programmers.ticketparis.domain
