server:
  port: 8080

spring:
  # DATABASE 기본 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ticketparis
    username: sa

  # H2 콘솔 접속 허용 설정
  h2:
    console:
      enabled: true
      path: /h2-console
