server:
  port: 8080

spring:
  # DATABASE 기본 설정
  datasource:
    driver-class-name: ${DATABASE_LOCAL_MYSQL_CLASSNAME}
    url: jdbc:mysql://localhost:3306/ticketparis
    username: root
    password: best14##

