server:
  port: 8080

spring:
  # DATABASE 기본 설정
  datasource:
    driver-class-name: ${DATABASE_LOCAL_MYSQL_CLASSNAME}
    url: ${DATABASE_LOCAL_MYSQL_URL}
    username: ${DATABASE_LOCAL_MYSQL_USERNAME}
    password: ${DATABASE_LOCAL_MYSQL_PASSWORD}
